#!/bin/bash

# Ignore shellcheck SC2154
# SC2154: var is referenced but not assigned

# Update the package index
sudo apt-get update

# Install Nginx
sudo apt-get install -y nginx

# Get the hostname of the server
HOSTNAME=$(hostname)

# Configure Nginx to include the custom header
sudo sed -i "/server_name _;/a \\\n\t# Add custom header\n\tadd_header X-Served-By $HOSTNAME;" /etc/nginx/sites-available/default

# Restart Nginx to apply the changes
sudo systemctl restart nginx
