#!/usr/bin/env bash
# Install and configure HAProxy on lb-01 server
# Configure HAProxy to send traffic to web-01 and web-02
# Distribute requests using a roundrobin algorithm
# Make sure that HAProxy can be managed via an init script

# Update package list and install HAProxy
sudo apt-get -y update
sudo apt-get -y install haproxy

# Create the HAProxy configuration
server_config="
frontend main
    bind *:80
    default_backend servers

backend servers
    balance roundrobin
    server web-01 54.146.84.46:80 check
    server web-02 52.204.62.163:80 check
"

# Backup the original HAProxy config file
sudo cp /etc/haproxy/haproxy.cfg /etc/haproxy/haproxy.cfg.bak

# Write the new configuration to HAProxy config file
echo "$server_config" | sudo tee /etc/haproxy/haproxy.cfg

# Enable HAProxy to be started by init script
echo "ENABLED=1" | sudo tee /etc/default/haproxy

# Restart HAProxy service to apply the changes
sudo service haproxy restart
